//
//  CMPConfiguration.h
//  Computop
//
//  Created by Thomas Segkoulis on 07/09/16.
//  Copyright © 2016 Computop GmbH. All rights reserved.
//

#import <Foundation/Foundation.h>

/**
 CMPConfiguration
 
 The CMPConfiguration class encapsulates all Merchant & App related data, generated by Computop.
 
 */
@interface CMPConfiguration : NSObject

/**
 Alphanumerical value which uniquely identifies the merchant within the Paygate
 */
+ (NSString *)merchantID;
+ (void) setMerchantID: (NSString *)newMerchandID;

/**
 Identifies the merchant, as previously agreed with Apple.  Must match one of the merchant
 identifiers in the application's entitlement.
 */
+ (NSString *)merchantAppleID;
+ (void) setMerchantAppleID: (NSString *)newMerchandID;

/**
 Merchant's auth request url
 */
+ (NSString *)authURL;
+ (void) setAuthURL: (NSString *)newAuthURL;

/**
 Specifies Official Account ID assigned by WeChat
 */
+ (NSString *)appID;

/**
 Specifies vendor ID assigned by WeChat Payment
 */
+ (NSString *)WeChatmchID;

/**
 Specifies payment assigned sub-business number
 */
+ (NSString *)WeChatsubMchID;

/**
 Empty description
 */
+ (NSString *)WeChatkey;

// TODO: add description
+ (void)setAppID:(NSString *)newAppID
           WeChatmchID:(NSString *)newMchID
        WeChatsubMchID:(NSString *)newSubMchID
             WeChatkey:(NSString *)newKey;

+ (void)registerApp: (NSString *)app;

+ (BOOL)handleOpenURL:(NSURL *) url;


/**
 HMAC key
 */
+ (NSString *)hmacKey;
+ (void) setHmacKey: (NSString *)newHmacKey;


@end
