//
//  CMPConfiguration.h
//  Computop
//
//  Created by Thomas Segkoulis on 07/09/16.
//  Copyright © 2016 Computop GmbH. All rights reserved.
//

#import <Foundation/Foundation.h>
/**
 CMPConfiguration
 
 The CMPConfiguration class encapsulates all Merchant & App related data, generated by Computop.

 */

typedef struct {
    __unsafe_unretained NSString* applicationID;
    __unsafe_unretained NSString* key;
    __unsafe_unretained NSString* mchID;
    __unsafe_unretained NSString* subMchID;
} WeChatParamStructure;

@interface CMPConfiguration : NSObject

/**
 Alphanumerical value which uniquely identifies the merchant within the Paygate
 */

+ (NSString *)merchantID;
+ (void) setMerchantID: (NSString *)newMerchandID;

/**
 Identifies the merchant, as previously agreed with Apple.  Must match one of the merchant
 identifiers in the application's entitlement.
 */
+ (NSString *)merchantAppleID;
+ (void) setMerchantAppleID: (NSString *)newMerchandID;

/**
 Merchant's auth request url
 */
+ (NSString *)authURL;
+ (void) setAuthURL: (NSString *)newAuthURL;


+ (void)registerApp: (NSString *)app;

+ (BOOL)handleOpenURL:(NSURL *) url;

/**
 HMAC key
 */
+ (NSString *)hmacKey;
+ (void) setHmacKey: (NSString *)newHmacKey;

+ (WeChatParamStructure *) WeChat;
+ (void)setWechatParams: (WeChatParamStructure *)WeChat;

@end
